//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniStoreWeb.Pages
{


    public partial class OrderDetails
    {

        /// <summary>
        /// lblOrderNumber control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblOrderNumber;

        /// <summary>
        /// lblPlacedAt control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblPlacedAt;

        /// <summary>
        /// lblRegion control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblRegion;

        /// <summary>
        /// lblPaymentMethod control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblPaymentMethod;

        /// <summary>
        /// lblOrderTotal control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblOrderTotal;

        /// <summary>
        /// lblCarrier control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblCarrier;

        /// <summary>
        /// lblEstimatedDelivery control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblEstimatedDelivery;

        /// <summary>
        /// rptOrderItems control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptOrderItems;
    }
}
