//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniStoreWeb.Pages
{


    public partial class Staff
    {

        /// <summary>
        /// lblStaffWelcome control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblStaffWelcome;

        /// <summary>
        /// btnStaffLogout control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnStaffLogout;

        /// <summary>
        /// lblProductCount control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblProductCount;

        /// <summary>
        /// lblStaffMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblStaffMessage;

        /// <summary>
        /// txtNewName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtNewName;

        /// <summary>
        /// ddlNewCategory control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlNewCategory;

        /// <summary>
        /// txtNewPrice control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtNewPrice;

        /// <summary>
        /// txtNewStockQuantity control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtNewStockQuantity;

        /// <summary>
        /// txtNewImage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtNewImage;

        /// <summary>
        /// txtNewDescription control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtNewDescription;

        /// <summary>
        /// ddlNewInStock control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlNewInStock;

        /// <summary>
        /// ddlNewFeatured control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlNewFeatured;

        /// <summary>
        /// btnAddProduct control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnAddProduct;

        /// <summary>
        /// gvProducts control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvProducts;
    }
}
