//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniStoreWeb.AdrianServiceReference {


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AdrianServiceReference.IShippingService")]
    public interface IShippingService {

        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShippingService/CalculateShipping", ReplyAction="http://tempuri.org/IShippingService/CalculateShippingResponse")]
        decimal CalculateShipping(decimal subtotal, string region);

        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShippingService/CalculateShipping", ReplyAction="http://tempuri.org/IShippingService/CalculateShippingResponse")]
        System.Threading.Tasks.Task<decimal> CalculateShippingAsync(decimal subtotal, string region);
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IShippingServiceChannel : MiniStoreWeb.AdrianServiceReference.IShippingService, System.ServiceModel.IClientChannel {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ShippingServiceClient : System.ServiceModel.ClientBase<MiniStoreWeb.AdrianServiceReference.IShippingService>, MiniStoreWeb.AdrianServiceReference.IShippingService {

        public ShippingServiceClient() {
        }

        public ShippingServiceClient(string endpointConfigurationName) :
                base(endpointConfigurationName) {
        }

        public ShippingServiceClient(string endpointConfigurationName, string remoteAddress) :
                base(endpointConfigurationName, remoteAddress) {
        }

        public ShippingServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
                base(endpointConfigurationName, remoteAddress) {
        }

        public ShippingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress) {
        }

        public decimal CalculateShipping(decimal subtotal, string region) {
            return base.Channel.CalculateShipping(subtotal, region);
        }

        public System.Threading.Tasks.Task<decimal> CalculateShippingAsync(decimal subtotal, string region) {
            return base.Channel.CalculateShippingAsync(subtotal, region);
        }
    }
}
