//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniStoreWeb.BellaServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BellaServiceReference.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDiscountedTotal", ReplyAction="http://tempuri.org/IService1/GetDiscountedTotalResponse")]
        decimal GetDiscountedTotal(decimal subtotal, string couponCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDiscountedTotal", ReplyAction="http://tempuri.org/IService1/GetDiscountedTotalResponse")]
        System.Threading.Tasks.Task<decimal> GetDiscountedTotalAsync(decimal subtotal, string couponCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCouponDescription", ReplyAction="http://tempuri.org/IService1/GetCouponDescriptionResponse")]
        string GetCouponDescription(string couponCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCouponDescription", ReplyAction="http://tempuri.org/IService1/GetCouponDescriptionResponse")]
        System.Threading.Tasks.Task<string> GetCouponDescriptionAsync(string couponCode);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : MiniStoreWeb.BellaServiceReference.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<MiniStoreWeb.BellaServiceReference.IService1>, MiniStoreWeb.BellaServiceReference.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public decimal GetDiscountedTotal(decimal subtotal, string couponCode) {
            return base.Channel.GetDiscountedTotal(subtotal, couponCode);
        }
        
        public System.Threading.Tasks.Task<decimal> GetDiscountedTotalAsync(decimal subtotal, string couponCode) {
            return base.Channel.GetDiscountedTotalAsync(subtotal, couponCode);
        }
        
        public string GetCouponDescription(string couponCode) {
            return base.Channel.GetCouponDescription(couponCode);
        }
        
        public System.Threading.Tasks.Task<string> GetCouponDescriptionAsync(string couponCode) {
            return base.Channel.GetCouponDescriptionAsync(couponCode);
        }
    }
}
