//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniStoreWeb.Controls
{


    public partial class FeaturedProducts
    {

        /// <summary>
        /// lblCartActionMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblCartActionMessage;

        /// <summary>
        /// litFeaturedMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litFeaturedMessage;

        /// <summary>
        /// rptFeaturedProducts control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptFeaturedProducts;
    }
}
