//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniStoreWeb.Pages
{


    public partial class Cart
    {

        /// <summary>
        /// lblCartMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblCartMessage;

        /// <summary>
        /// pnlEmptyCart control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlEmptyCart;

        /// <summary>
        /// pnlCart control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlCart;

        /// <summary>
        /// rptCartItems control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptCartItems;

        /// <summary>
        /// lblItemCount control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblItemCount;

        /// <summary>
        /// lblSubtotal control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblSubtotal;

        /// <summary>
        /// btnProceedToCheckout control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnProceedToCheckout;

        /// <summary>
        /// btnClearCart control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnClearCart;
    }
}
