//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniStoreWeb.Pages
{


    public partial class Checkout
    {

        /// <summary>
        /// lblCheckoutMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblCheckoutMessage;

        /// <summary>
        /// pnlEmptyCheckout control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlEmptyCheckout;

        /// <summary>
        /// pnlCheckout control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlCheckout;

        /// <summary>
        /// ddlCouponCode control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlCouponCode;

        /// <summary>
        /// lblCouponDescription control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblCouponDescription;

        /// <summary>
        /// ddlShippingRegion control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlShippingRegion;

        /// <summary>
        /// optInfiniteMoney control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlInputRadioButton optInfiniteMoney;

        /// <summary>
        /// optFairyDust control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlInputRadioButton optFairyDust;

        /// <summary>
        /// optFaceCard control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlInputRadioButton optFaceCard;

        /// <summary>
        /// btnRefreshTotals control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnRefreshTotals;

        /// <summary>
        /// btnPlaceOrder control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnPlaceOrder;

        /// <summary>
        /// rptCheckoutItems control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptCheckoutItems;

        /// <summary>
        /// lblCheckoutSubtotal control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblCheckoutSubtotal;

        /// <summary>
        /// lblCheckoutDiscount control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblCheckoutDiscount;

        /// <summary>
        /// lblCheckoutShipping control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblCheckoutShipping;

        /// <summary>
        /// lblCheckoutTotal control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblCheckoutTotal;
    }
}
