//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniStoreWeb.Pages
{


    public partial class Member
    {

        /// <summary>
        /// lblWelcomeMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblWelcomeMessage;

        /// <summary>
        /// btnLogout control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnLogout;

        /// <summary>
        /// lnkTabOverview control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HyperLink lnkTabOverview;

        /// <summary>
        /// lnkTabFavorites control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HyperLink lnkTabFavorites;

        /// <summary>
        /// lnkTabOrders control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HyperLink lnkTabOrders;

        /// <summary>
        /// pnlOverview control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlOverview;

        /// <summary>
        /// lblMemberSince control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblMemberSince;

        /// <summary>
        /// lblCartCount control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblCartCount;

        /// <summary>
        /// lblOrderCount control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblOrderCount;

        /// <summary>
        /// lblSessionStart control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblSessionStart;

        /// <summary>
        /// pnlFavorites control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlFavorites;

        /// <summary>
        /// ddlFavoriteProduct control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlFavoriteProduct;

        /// <summary>
        /// btnAddFavorite control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnAddFavorite;

        /// <summary>
        /// btnClearFavorites control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnClearFavorites;

        /// <summary>
        /// lblFavoriteMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblFavoriteMessage;

        /// <summary>
        /// gvFavorites control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvFavorites;

        /// <summary>
        /// pnlOrders control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlOrders;

        /// <summary>
        /// gvOrders control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvOrders;
    }
}
