//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniStoreWeb.Pages
{


    public partial class OrderConfirmation
    {

        /// <summary>
        /// lblOrderNumber control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblOrderNumber;

        /// <summary>
        /// lblPlacedAt control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblPlacedAt;

        /// <summary>
        /// lblPaymentMethod control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblPaymentMethod;

        /// <summary>
        /// lblRegion control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblRegion;

        /// <summary>
        /// lblCouponUsed control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblCouponUsed;

        /// <summary>
        /// lblReceiptSubtotal control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblReceiptSubtotal;

        /// <summary>
        /// lblReceiptDiscount control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblReceiptDiscount;

        /// <summary>
        /// lblReceiptShipping control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblReceiptShipping;

        /// <summary>
        /// lblReceiptTotal control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblReceiptTotal;

        /// <summary>
        /// rptReceiptItems control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptReceiptItems;
    }
}
