//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniStoreWeb
{


    public partial class SiteMaster
    {

        /// <summary>
        /// cartBadge control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl cartBadge;

        /// <summary>
        /// lblCartCount control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblCartCount;

        /// <summary>
        /// MainContent control.
        /// </summary>
        protected global::System.Web.UI.WebControls.ContentPlaceHolder MainContent;
    }
}
